### PR TITLE
chore: Upgrade to Expo SDK 48

### LINKED ISSUE #186: Upgrade to Expo SDK 48

### PR DESCRIPTION
**Pull request by ofredstie**
Upgraded Expo and related packages to the latest version. @types/react-native could be removed since Typescript is automatically included in the react-native package. Expo-random is deprecated and replaced by expo-crypto.

Closes #186

### CODE REVIEW

**Comment by ofredstie** [comment]
Expo-doctor reported some issues with invalid versions of @expo/config-plugins. 

image

**Review by HaakonSvane — APPROVED** [review]
Looks very good 👌 
You seem to have done all the migration steps as per the docs 🔥

**Review by HaakonSvane — APPROVED** [review]
Looks very good 👌 
You seem to have done all the migration steps as per the docs 🔥

**Review by HaakonSvane — APPROVED** [review]
Nice

**Pull request merged**
